services:
  - type: web
    name: malicious-url-detection-api
    env: python
    buildCommand: cd backend && chmod +x install_deps.sh && ./install_deps.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    healthCheckPath: /health
